#!/usr/bin/env bash
#
# Regenerates src/media/* (what the app imports) from media-src/* (originals).
#
# Why this exists:
#   The originals are 24MP camera JPEGs; the layout shows them at 400-900px.
#   Before this script the repo shipped 27MB of assets, including two 12MB
#   Figma SVG exports with full-resolution rasters base64-embedded inside them.
#   media-src/ is deliberately outside src/ so Create React App never bundles
#   it -- only src/media/ reaches the browser.
#
# Requires: ImageMagick 6 (`convert`) with the libwebp delegate.
# Run from the repo root:  ./scripts/optimize-media.sh

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SRC="$ROOT/media-src"
OUT="$ROOT/src/media"

if ! convert -list format | grep -q 'WEBP.*rw'; then
  echo "error: ImageMagick has no WebP write support (needs the libwebp delegate)." >&2
  exit 1
fi

mkdir -p "$OUT"
# Only clear generated *.webp files -- images.js (the manifest that resolves
# them for components) lives in this same folder and must survive a rerun.
find "$OUT" -maxdepth 1 -name '*.webp' -delete

# The room photos were shot under mixed fluorescent light with the windows
# behind the subjects, so faces come out several stops down. This lifts the
# shadows without clipping the ceiling panels, warms saturation a touch, and
# applies a light capture sharpen. Tuned by eye against the originals.
GRADE=(-gamma 1.55 -contrast-stretch 0.2x0.4% -modulate 100,108,100 -unsharp 0x1+0.5+0)

# emit <infile> <out-basename> <gravity|-> <crop-geometry|-> <width>...
# Crops were measured off the originals, not guessed: in every room photo the
# subjects sit in a band and the rest of the frame is ceiling or floor tile.
emit() {
  local in="$1" base="$2" grav="$3" crop="$4"; shift 4
  local w args
  for w in "$@"; do
    args=(convert "$in" -auto-orient)
    [ "$grav" != "-" ] && args+=(-gravity "$grav")
    [ "$crop" != "-" ] && args+=(-crop "$crop" +repage)
    args+=("${GRADE[@]}" -resize "${w}x" -strip -quality 78
           -define webp:method=6 "$OUT/${base}-${w}.webp")
    "${args[@]}"
    printf '  %-26s %6s %s\n' "${base}-${w}.webp" \
      "$(du -h "$OUT/${base}-${w}.webp" | cut -f1)" \
      "$(identify -format '%wx%h' "$OUT/${base}-${w}.webp")"
  done
}

# Wide band under the hero. Original is 42% empty ceiling; keep the bottom 58%.
# 2400w included for large desktop screens so the hero image isn't upscaled.
echo "==> Cohort group photo (hero band, 2.6:1)"
emit "$SRC/cohort-group.jpg" "cohort-group" south "100%x58%+0+0" 800 1200 1800 2400

# Subjects occupy 38%-95% of the frame height. Cropped to 4:3 around the
# front rows so it can sit in a column beside text.
echo "==> Classroom photo (about, 4:3)"
emit "$SRC/classroom.jpg" "classroom" - "3040x2280+380+1520" 560 840 1120

# session-1 is the only portrait original; cropped to match the others so the
# gallery does not letterbox one slide.
echo "==> Session photos (gallery, 3:2)"
emit "$SRC/session-1.jpg" "session-1" - "1920x1280+0+430" 600 900
for n in 2 3 4 5; do
  emit "$SRC/session-$n.jpg" "session-$n" - - 600 900
done

# Logo art: no grade, no crop, preserve the flat white background cleanly.
echo "==> Client logos (no grade, no crop -- these are flat vector-ish art)"
convert "$SRC/client-aipl.jpg" -auto-orient -resize 489x -strip -quality 90 \
  -define webp:method=6 "$OUT/client-aipl.webp"
printf '  %-26s %6s\n' "client-aipl.webp" "$(du -h "$OUT/client-aipl.webp" | cut -f1)"

for name in uba vitafoam fruitylife mycil; do
  convert "$SRC/client-${name}.png" -resize 400x400 -strip -quality 90 \
    -define webp:method=6 "$OUT/client-${name}.webp"
  printf '  %-26s %6s\n' "client-${name}.webp" "$(du -h "$OUT/client-${name}.webp" | cut -f1)"
done

# Site logo, from public/logo-main.png (the master, not itself generated by
# this script). Emitted at the two sizes the header/footer actually request.
echo "==> Site logo"
for w in 96 192; do
  convert "$ROOT/public/logo-main.png" -resize "${w}x${w}" -strip -quality 92 \
    -define webp:method=6 "$OUT/logo-${w}.webp"
  printf '  %-26s %6s\n' "logo-${w}.webp" "$(du -h "$OUT/logo-${w}.webp" | cut -f1)"
done

echo
echo "src/media is now $(du -sh "$OUT" | cut -f1) across $(find "$OUT" -type f | wc -l) files."
